<img src="https://rhyme.com/assets/img/logo-dark.png" align="center"> <h2 align="center">Logistic Regression: A Sentiment Analysis Case Study</h2>

### Introduction
___

- IMDB movie reviews dataset
- http://ai.stanford.edu/~amaas/data/sentiment
- Contains 25000 positive and 25000 negative reviews
<img src="https://i.imgur.com/lQNnqgi.png" align="center">
- Contains at most reviews per movie
- At least 7 stars out of 10 $\rightarrow$ positive (label = 1)
- At most 4 stars out of 10 $\rightarrow$ negative (label = 0)
- 50/50 train/test split
- Evaluation accuracy

<b>Features: bag of 1-grams with TF-IDF values</b>:
- Extremely sparse feature matrix - close to 97% are zeros

 <b>Model: Logistic regression</b>
- $p(y = 1|x) = \sigma(w^{T}x)$
- Linear classification model
- Can handle sparse data
- Fast to train
- Weights can be interpreted
<img src="https://i.imgur.com/VieM41f.png" align="center" width=500 height=500>

### Task 1: Loading the dataset
---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./data/movie_data.csv')
df

review  sentiment
0      In 1974, the teenager Martha Moxley (Maggie Gr...          1
1      OK... so... I really like Kris Kristofferson a...          0
2      ***SPOILER*** Do not read this, if you think a...          0
3      hi for all the people who have seen this wonde...          1
4      I recently bought the DVD, forgetting just how...          0
5      Leave it to Braik to put on a good show. Final...          1
6      Nathan Detroit (Frank Sinatra) is the manager ...          1
7      To understand "Crash Course" in the right cont...          1
8      I've been impressed with Chavez's stance again...          1
9      This movie is directed by Renny Harlin the fin...          1
10     I once lived in the u.p and let me tell you wh...          0
11     Hidden Frontier is notable for being the longe...          1
12     It's a while ago, that I have seen Sleuth (197...          0
13     What is it about the French? First, they (appa...          0
14     This very strange movie is unlike anything mad...          1
15     I saw this movie on the strength of the single...          0
16     There are some great philosophical questions. ...          0
17     I was cast as the Surfer Dude in the beach sce...          1
18     I had high hopes for this one until they chang...          0
19     Set in and near a poor working class town in t...          1
20     Opulent sets and sumptuous costumes well photo...          0
21     i saw the film and i got screwed, because the ...          0
22     I'm getting a little tired of people misusing ...          0
23     How offensive! Those who liked this movie have...          0
24     What else can you say about this movie,except ...          0
25     Certain aspects of Punishment Park are less th...          1
26     First of all, I'd like to tell you that I'm in...          0
27     You should not take what I am about to say lig...          1
28     I love the Jurassic Park movies, they are thre...          0
29     The first series of Lost kicked off with a ban...          1
...                                                  ...        ...
49970  Tom Fontana's unforgettable "Oz" is hands down...          1
49971  Last weekend I bought this 'zombie movie' from...          0
49972  I watched the first few moments on TCM a few y...          1
49973  I saw this movie for the first time in 1988 wh...          1
49974  Al Pacino? Kim Basinger? Tea Leoni? Ryan O'Nea...          0
49975  Stanwyck at her villainous best, Robinson her ...          1
49976  An allegation of aggravated sexual assault alo...          0
49977  i thought this movie was wonderfully plotted i...          1
49978  Just like most people, I couldn't wait to see ...          0
49979  Dark comedy? Gallows humor? How does one make ...          1
49980  ****Probably will contain spoilers****<br /><b...          0
49981  I must be that one guy in America that didn't ...          0
49982  THE PLOT: A trucker (Kristofferson) battles a ...          0
49983  The Ladies Man is laugh out loud funny, with a...          1
49984  Well, the artyfartyrati of Cannes may have lik...          0
49985  The director was probably still in his early l...          0
49986  You know when you're on the bus and someone de...          0
49987  Five minutes into this movie you realize that ...          0
49988  ...If you've been laughing too much for a long...          0
49989  I love dissing this movie. My peers always try...          0
49990  OK. I think the TV show is kind of cute and it...          0
49991  Big disappointment. CLASH BY NIGHT is much to ...          0
49992  Cassidy(Kacia Brady)puts a gun in her mouth bl...          0
49993  With rapid intercutting of scenes of insane pe...          1
49994  When "Girlfight" came out, the reviews praised...          1
49995  OK, lets start with the best. the building. al...          0
49996  The British 'heritage film' industry is out of...          0
49997  I don't even know where to begi

In [3]:
df.review[0]

'In 1974, the teenager Martha Moxley (Maggie Grace) moves to the high-class area of Belle Haven, Greenwich, Connecticut. On the Mischief Night, eve of Halloween, she was murdered in the backyard of her house and her murder remained unsolved. Twenty-two years later, the writer Mark Fuhrman (Christopher Meloni), who is a former LA detective that has fallen in disgrace for perjury in O.J. Simpson trial and moved to Idaho, decides to investigate the case with his partner Stephen Weeks (Andrew Mitchell) with the purpose of writing a book. The locals squirm and do not welcome them, but with the support of the retired detective Steve Carroll (Robert Forster) that was in charge of the investigation in the 70\'s, they discover the criminal and a net of power and money to cover the murder.<br /><br />"Murder in Greenwich" is a good TV movie, with the true story of a murder of a fifteen years old girl that was committed by a wealthy teenager whose mother was a Kennedy. The powerful and rich famil

## <h2 align="center">Bag of words / Bag of N-grams model</h2>

### Task 2: Transforming documents into feature vectors

Below, we will call the fit_transform method on CountVectorizer. This will construct the vocabulary of the bag-of-words model and transform the following three sentences into sparse feature vectors:
1. The sun is shining
2. The weather is sweet
3. The sun is shining, the weather is sweet, and one and one is two


In [9]:
from sklearn.feature_extraction.text import CountVectorizer
count=CountVectorizer()

docs = np.array(['The sun is shining',
                'The weather is sweet',
                'The sun is shining, the weather is sweet, and one and one is two'])
bag = count.fit_transform(docs)

In [5]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [10]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


Raw term frequencies: *tf (t,d)*—the number of times a term t occurs in a document *d*

### Task 3: Word relevancy using term frequency-inverse document frequency

$$\text{tf-idf}(t,d)=\text{tf (t,d)}\times \text{idf}(t,d)$$

$$\text{idf}(t,d) = \text{log}\frac{n_d}{1+\text{df}(d, t)},$$

where $n_d$ is the total number of documents, and df(d, t) is the number of documents d that contain the term t.

In [14]:
from sklearn.feature_extraction.text import TfidfTransformer
np.set_printoptions(precision=2)
tfidf = TfidfTransformer(use_idf = True, norm = 'l2', smooth_idf = True)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]


The equations for the idf and tf-idf that are implemented in scikit-learn are:

$$\text{idf} (t,d) = log\frac{1 + n_d}{1 + \text{df}(d, t)}$$
The tf-idf equation that is implemented in scikit-learn is as follows:

$$\text{tf-idf}(t,d) = \text{tf}(t,d) \times (\text{idf}(t,d)+1)$$

### Task 4: Data Preparation

In [16]:
df.loc[0,'review'][-50:]

'is seven.<br /><br />Title (Brazil): Not Available'

In [21]:
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower()) +\
        ' '.join(emoticons).replace('-', '')
    return text

In [18]:
preprocessor(df.loc[0,'review'][-50:])

'is seven title brazil not available'

In [24]:
preprocessor('</html> is :-) lols')

' is lols:)'

In [27]:
df.review = df.review.apply(preprocessor)
df.review[68]

'i thought it would at least be aesthetically beautiful it was slow pretentious and boring i almost fell asleep there are some decent songs but there is this one song at the end which is just some guy yelling out yaowwww while someone taps randomly on a wooden object that being said there are some pretty songs but it s not worth seeing hte movie over go on itunes they have the album preview it and choose the good ones half the movie is some guy making tea well that s a slight exaggeration but you ll see what i mean if you see it that being said don t see it '

### Task 5: Tokenization of documents

In [28]:
from nltk.stem.porter import PorterStemmer

porter = PorterStemmer()
porter

<PorterStemmer>

In [29]:
def tokenizer(text):
    return text.split()

In [30]:
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [31]:
tokenizer('so this is an example sentance to test the function it could be whatever')

['so',
 'this',
 'is',
 'an',
 'example',
 'sentance',
 'to',
 'test',
 'the',
 'function',
 'it',
 'could',
 'be',
 'whatever']

In [32]:
tokenizer('runners like running hence they run and they will keep running')

['runners',
 'like',
 'running',
 'hence',
 'they',
 'run',
 'and',
 'they',
 'will',
 'keep',
 'running']

In [34]:
tokenizer_porter('runners like running hence they run and they will keep running')

['runner',
 'like',
 'run',
 'henc',
 'they',
 'run',
 'and',
 'they',
 'will',
 'keep',
 'run']

In [36]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/rhyme/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [39]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
[w for w in tokenizer_porter('a runners like running and runs a lot')[-10:] if w not in stop]

['runner', 'like', 'run', 'run', 'lot']

### Task 6: Transform Text Data into TF-IDF Vectors

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(strip_accents=None,
                       lowercase=False,
                       preprocessor=None,
                       tokenizer=tokenizer_porter,
                       use_idf= True,
                        norm = 'l2',
                        smooth_idf = True
                       )
y = df.sentiment.values
X = tfidf.fit_transform(df.review)

In [42]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 1, test_size = 0.5,shuffle = False)

### Task 7: Document Classification using Logistic Regression

In [43]:
import pickle
from sklearn.linear_model import LogisticRegressionCV

clf = LogisticRegressionCV(cv=5,
                          scoring = 'accuracy',random_state = 0,
                          n_jobs = -1,
                          verbose = 3,
                          max_iter=300).fit(X_train,y_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  2.5min finished


In [44]:
saved_model = open('saved_model.sav','wb')
pickle.dump(clf,saved_model)
saved_model.close()

### Task 8: Model Evaluation

In [46]:
file_name = 'saved_model.sav'
saved_clf = pickle.load(open(file_name,'rb'))

In [48]:
saved_clf.score(X_test,y_test)

/home/rhyme/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:1926: ChangedBehaviorWarning: The long-standing behavior to use the accuracy score has changed. The scoring parameter is now used. This warning will disappear in version 0.22.
  ChangedBehaviorWarning)


0.89608